### ISSUE TITLE
SassCompiler.Compile crashes

### ISSUE THREAD

**Issue by Untit1ed** [darrenkopp/libsass-net#21]
My app crashes every time I try to compile anything with SassCompiler.Compile (CompileFile works fine).

Here is what I get when I pass `"body{}"` as an input string into `Compile`:
![image](https://cloud.githubusercontent.com/assets/1929699/7525977/c37ae7d2-f4c2-11e4-9671-7ca4239f255a.png)

Just tried with the latest LibSass - still the same problem.

**Comment by aviatrix** [comment]
This should be fixed with the upcoming nuget package release, however if you download & compile the source & reference it manually, it will work ( unless i'm totally misreading the issue at hand)

**Comment by Untit1ed** [comment]
I wasn't even aware there's a nuget package. I was using a compiled master code when it happened.

**Comment by aviatrix** [comment]
Can you provide some more info about this ? if you can upload the test project iil take a look at it and see what's going on.

**Comment by Untit1ed** [comment]
There's not much to show, it's basically just:
```c#
var inputString = "body{}";
SassCompiler compiler = new SassCompiler();
string result = compiler.Compile(inputString);
```

I added a test project
https://github.com/Untit1ed/libsass-net/blob/master/Test/Program.cs

**Comment by IDDesigns** [comment]
This still appears to be a problem in version 3.2.4. 

using:

```
styleSheet = _compiler.Compile("@import \"theme.scss\";" + Environment.NewLine, OutputStyle.Compressed, false, 5, new[] { baseTheme }) + Environment.NewLine + styleSheet;
```

results in 

One or more arguments are invalid (Exception from HRESULT: 0x80000003)

This works fine when running against 3.1.0.

**Comment by darrenkopp** [comment]
This should be resolved now with the latest version on nuget (3.2.4.1)
